version: '3.9'

services:
  celery:
    platform: linux/amd64
    build: .
    container_name: 'celery'
    command: >
      bash -c "celery -A eva.isiao worker --beat --loglevel=info"
    volumes:
      - .:/code
      - ./.env_docker:/app/.env
    depends_on:
      - backend
  backend:
    build: .
    container_name: 'backend'
    platform: linux/amd64
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn portal.wsgi -b :8000"
    ports:
      - '8000:8000'
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
      - ./.env_docker:/app/.env

volumes:
  static_value:
  media_value: