version: '3.9'

services:
  celery:
    platform: linux/amd64
    build: .
    container_name: 'celery'
    command: >
      bash -c "celery -A eva.isiao worker --beat --loglevel=info"
    volumes:
      - .:/code
      - ./.env.docker:/app/.env
    links:
      - redis
    depends_on:
      - backend
      - redis
  backend:
    build: .
    container_name: 'backend'
    platform: linux/amd64
    depends_on:
      - db
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn portal.wsgi -b :8000"
    ports:
      - '8000:8000'
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
      - ./.env.docker:/app/.env
  db:
    restart: always
    image: postgres:15.0-alpine
    container_name: portal_db
    env_file:
      - ./.env.docker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    platform: linux/amd64
    image: redis/redis-stack:latest
    container_name: redis
    expose:
      - '6379'
    ports:
      - '9999:8001'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  static_value:
  media_value:
  redis_data: