version: '3.9'

services:
  celery:
    platform: linux/amd64
    build: .
    container_name: 'celery'
    command: >
      bash -c "celery -A eva.isiao worker --beat --loglevel=info"
    env_file:
      - .env.docker
    volumes:
      - .:/code
      - ./.env.docker:/code/.env
    links:
      - redis
    depends_on:
      - backend
      - redis
  backend:
    build: .
    container_name: 'api'
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn portal.wsgi -b :8000"
    ports:
      - '8000:8000'
    env_file:
      - .env.docker
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
      - ./.env.docker:/code/.env
  redis:
    platform: linux/amd64
    image: redis/redis-stack:latest
    container_name: redis
    expose:
      - '6379'
    ports:
      - '9999:8001'
    volumes:
      - redis_data:/data
  zammad_db_replica:
    platform: linux/amd64
    image: postgres:14.0-alpine
    container_name: zammad_replica
    environment:
      POSTGRES_DB: "zammad"
      POSTGRES_USER: "report"
      POSTGRES_PASSWORD: "123456"
    expose:
      - '5621'
    ports:
      - '5621:5432'
    volumes:
      - zammad_replica:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_value:
  media_value:
  redis_data:
  zammad_replica: